# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift


name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Utility Build
      run: |
        cd source/DIDClientSDK
        xcodebuild build -scheme DIDUtilitySDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=15.6'
    - name: Utility Test
      run: |
        cd source/DIDClientSDK
        xcodebuild test -scheme DIDUtilitySDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'        
    - name: DataModel Build
      run: |
        cd source/DIDClientSDK
        xcodebuild build -scheme DIDDataModelSDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=15.6'
    - name: DataModel Test
      run: |
        cd source/DIDClientSDK
        xcodebuild test -scheme DIDDataModelSDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'        
    - name: Core Build
      run: |
        cd source/DIDClientSDK
        xcodebuild build -scheme DIDCoreSDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=15.6'
    - name: Core Test
      run: |
        cd source/DIDClientSDK
        xcodebuild test -scheme DIDCoreSDK -workspace DIDClientSDK.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'   
